### ISSUE TITLE
blue-green-deploy is missing

### ISSUE THREAD

**Issue by ldbl** [argoproj/argocd-example-apps#17]
Hi there , 
Where is this example blue-green-deploy I got 404 error. 

P.S 
I found it. It's just not in master branch.

**Comment by alexmt** [comment]
Hello @ldbl . The blue-green-deploy was deleted because we've realized that scripting this logic is not the best way to do it. Instead, we've implemented a controller which implements blue-green and canary deployment strategies: https://github.com/argoproj/argo-rollouts .

@dthomson25 , the Argo Rollouts example should be added to this repo.
